[book]
title = "Taming sox"
authors = ["Bart Massey", "Claude Code"]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/pdx-cs-sound/taming-sox"
